### PR TITLE
Added copy to clipboard functionality

### LINKED ISSUE #69: allow users to copy code snippets to clipboard with a single button
https://clipboardjs.com/ is a non flash based method to do this

Opened via [gitter](https://gitter.im/coala/coala/maintainers/?at=588f24a4c0f28dd8625ee57d) by @sudheesh001

### PR DESCRIPTION
**Pull request by abhishalya**
Added "copy to clipboard" button to copy code snippets.

Fixes #69 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by abhishalya** [comment]
@Man-Jain The url is obviously incorrect :sweat_smile: Can you give me some example of what ideal commit message should be here.
Would "Added single button to allow users to copy code snippets to clipboard" work?

**Comment by Man-Jain** [comment]
> @Man-Jain The url is obviously incorrect  I wen't through [commit guidelines](http://coala.io/commit). Can you give me some example of what ideal commit message should be here.
> Would "Added single button to allow users to copy code snippets to clipboard" work?

Well you can do 

coalaonline.html: Add copy to clipboard button or something else

**Comment by abhishalya** [comment]
@Man-Jain Would this work?

**Comment by Man-Jain** [comment]
> @Man-Jain Would this work?

Nope did you read the commit guidelines? Commit message must contain the issue link. Also a description  must be added in your case

**Comment by abhishalya** [comment]
@Man-Jain Oops, I have added the required things now. Can you check?

**Comment by jayvdb** [comment]
ack https://github.com/coala/landing-frontend/pull/287/commits/89ab69cf410ece81359f89b36c6ab772f713ffb2

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
