### PR TITLE
style.css: Improve line-height and height of badge

### PR DESCRIPTION
**Pull request by hemangsk**
Fixes https://github.com/coala/landing-frontend/issues/50

### CODE REVIEW

**Comment by hemangsk** [comment]
@gkrishnan724 exactly :smiley: fixing it

**Comment by hemangsk** [comment]
@gkrishnan724 I'm not able to reproduce this, I tried the width from your screenshot 1366px, and this change is inside media query of max-width: 768px, so I can't see why it would change in 1366px

**Comment by gkrishnan724** [comment]
@hemangsk  Yeah, you are right sorry. I probably put this wrong did not see the media query 

By the way how do you test changes from a PR? I just copy pasted the code and put it in my styles.css. Realised that was a really wrong way to do it :P

**Comment by gkrishnan724** [comment]
ack   b9b1c74

**Comment by hemangsk** [comment]
Oh okay 😃 
So we can click on this link *view command line instructions*
It is at bottom of this PR inside the box  (the same box where "Rebase and Merge" button is)
And just follow the step 1,  it will fetch us the commits of this PR  😃  🚀  cool isnt it

**Comment by gkrishnan724** [comment]
Oh cool, so is it only available for people with write access?

**Comment by hemangsk** [comment]
I am not sure about it, but if that's the case it'll  just require to clone this fork and to checkout the patch-8 branch I guess.

**Comment by hemangsk** [comment]
reack 621c61b

**Comment by hemangsk** [comment]
@rultor merge

**Pull request merged**
