### PR TITLE
Hemangsk/preloader

### PR DESCRIPTION
**Pull request by hemangsk**
wrt 	354a026
screen shot 2017-01-29 at 8 10 09 pm

wrt f91b6e3

### CODE REVIEW

**Comment by meetmangukiya** [comment]
I think we should increase the height to 1.5H where H is the current height, it is completely upto you though, I'm just being quite picky I feel :P

**Comment by meetmangukiya** [comment]
Can't see what changes you made to the try online in the screenshot :/

**Comment by hemangsk** [comment]
@meetmangukiya let me zoom it a bit  😛 
screen shot 2017-01-29 at 8 10 09 pm

**Comment by meetmangukiya** [comment]
damn, what is wrong with my eyes! :worried: Sorry for that! Also, you didn't resize ?

**Comment by hemangsk** [comment]
oops forgot about this one earlier!

**Comment by meetmangukiya** [comment]
Little padding from top ? LGTM though :+1:

**Comment by hemangsk** [comment]
feel the same, small change but makes it look better 👍  
screencapture-localhost-8080-1485708187946

**Pull request merged**
