### PR TITLE
languages.html: Add settings section

### PR DESCRIPTION
**Pull request by hemangsk**
screen shot 2017-02-03 at 1 04 32 pm

### CODE REVIEW

**Comment by sils** [comment]
@hemangsk can we have them in the body? We need the details including dscription and defaults as well

**Comment by sils** [comment]
generally there mustnt be less info about the bears than on coala.io/languages

**Comment by gkrishnan724** [comment]
@hemangsk  I just noticed that your change makes a scroll bar below modal 
screenshot from 2017-02-03 18-41-33

**Comment by gkrishnan724** [comment]
Seems, we need to open an issue for the Modal styling. It does not look good on small screens.
screenshot from 2017-02-03 18-47-57

**Comment by hemangsk** [comment]
@sils exactly that'll look much better in the body side, moving it
 @gkrishnan724 adding the settings and other metadata in the body section will resolve this modal issue too 👍 
Marking this one as WIP

**Comment by ankit01ojha** [comment]
@hemangsk  IMO you should also shift the `AUTHORS` and `AUTHOR EMAIL` which is overlapping the description of the bear to the left side as a card or at the bottom in one line at the end of the description.

**Pull request merged**
