### PR TITLE
style.css: Make labels look nice

### PR DESCRIPTION
**Pull request by ankit01ojha**
made the language labels look nice
Closed https://github.com/coala/landing-frontend/issues/63

### CODE REVIEW

**Comment by gkrishnan724** [comment]
@ankit01ojha It was suggested in the issue that you change `Python2 Python3 Python` to `Python2/3` which involves modifying the data. Maybe you could ask @hemangsk  on how to do that :)

**Comment by ankit01ojha** [comment]
@gkrishnan724 Sorry I forgot to change the `Python 2 Python 3` to `Python2/3` I only changed it look like  http://projects.coala.io/#/projects these labels.

**Comment by hemangsk** [comment]
@ankit01ojha as they are converted to chips already now, this PR can solve the issue of reordering the languages

**Comment by ankit01ojha** [comment]
@hemangsk I think this issue has been fixed, As In the new coala page labels are in chips form and are sorted too.

**Comment by sils** [comment]
yep this isn't longer needed indeed, thanks @ankit01ojha

**Pull request closed without merging**
