### PR TITLE
app.js: Path correction

### PR DESCRIPTION
**Pull request by gkrishnan724**
Closes: https://github.com/coala/landing-frontend/issues/36

### CODE REVIEW

**Comment by Makman2** [comment]
From gitter:
> changes look good, but please change the commit message according to our rules: http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html :)

**Comment by hemangsk** [comment]
This works as it should 😄  👍  I was wrong about angular looking for ```resources/js/app.js/partials/tabs/home.html```. The /partials and partial both are working fine with the HTTP server setup, and neither is working without server. 
I'd prefer /projects because it conveys that user should looks for partials folder inside the root directory and not is resources/js, but that's just me

**Comment by hemangsk** [comment]
ack 	e8817ce

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
