### PR TITLE
data/snippets: Improve support for new snippets

### PR DESCRIPTION
**Pull request by hemangsk**
- Adds option for loading more contributors 
screen shot 2017-01-28 at 7 32 33 pm

### CODE REVIEW

**Comment by hemangsk** [comment]
@gkrishnan724 fixed it, can you try it out now

**Comment by gkrishnan724** [comment]
ack  	fa53022   e2082a7  59983e7

**Comment by gkrishnan724** [comment]
ack  	eb7dce6   	bd82b2d

**Comment by gkrishnan724** [comment]
:+1:

**Comment by hemangsk** [comment]
@rultor merge

**Comment by hemangsk** [comment]
@rultor stop

**Comment by hemangsk** [comment]
reack 7e3d428 e8a0e84 fed5bad 2f87234 b233678

**Comment by hemangsk** [comment]
@rultor merge

**Pull request merged**
