### PR TITLE
partials/tabs/home.html: Be consistent with subheaders for different …

### PR DESCRIPTION
**Pull request by j0ack**
…OSes

Fixes https://github.com/coala/landing-frontend/issues/70

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by meetmangukiya** [comment]
ack f972097

**Comment by meetmangukiya** [comment]
reack f972097f3d9ad1927554f3da3eb2b075e2322dde

**Comment by hemangsk** [comment]
@j0ack can you remove ```partials/tabs/``` from your commit message and just keep ```home.html```. The commit shortlog is overflowing making it a bit difficult to understand

**Comment by j0ack** [comment]
@hemangsk sure do you want that I squash the commits ?

**Comment by hemangsk** [comment]
@j0ack your present shortlog :
```
partials/tabs/home.html: Be consistent with subheaders for different …  …
…OSes

```
is too long causing a line break and ```...```

If we make it a bit short by removing 'partials/tabs/'
```
home.html: Be consistent with subheaders for different OSes
```
then we'll have better readability 👍 😃

**Comment by hemangsk** [comment]
Perfect! needs a rebase and we're all set to merge it 🚀 
 [coala.io/rebase](http://coala.io/rebase)

**Comment by j0ack** [comment]
@hemangsk done :)

**Comment by hemangsk** [comment]
ack 93976f1

**Comment by hemangsk** [comment]
@rultor merge

**Pull request merged**
