### PR TITLE
Hemangsk/css

### PR DESCRIPTION
**Pull request by hemangsk**
Short Note

This has a lot of changes in all the partials file. These changes are large in number, but essentially they do only these three tasks,

- Remove Bootstrap's class and use MaterializeCSS grid classes.
- Use classes available in coalaCSS and restructures the divs accordingly if required.
- Indentation and removal of extra newlines.

It introduces the usage of coalaCSS via CDN link from rawgit. Its a CSS theme which we can use throughout web projects at coala. 

It will be really awesome if someone can help me test the changes! So to fetch these new changes and to test locally,

```
git clone https://github.com/coala/landing-frontend.git
cd landing-frontend
git fetch origin pull/169/head:hemangsk/css
git checkout hemangsk/css
```

```
python -m SimpleHTTPServer 8080 # python2
or
python3 -m http.server 8080 #python3
```

Visit localhost:8080 in browser to view the site running.
Thanks ☺️ 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by meetmangukiya** [comment]
I think we need more padding/margin both sides, right and left. After the change the website is full length, while currently it is not full length

**Comment by hemangsk** [comment]
Marking pending/review as discussed with @meetmangukiya  on Gitter

**Comment by sils** [comment]
coalaoldnew

to the left, the new one, it doesn't look as charming as the old one, also the centering on the front page is indeed a bit weird

**Comment by sils** [comment]
ack
2c63538 style.css: Remove unneeded CSS
0e813db tryonline: Use coala CSS and update markup
930021d languages.html: Use Materialize columns and Restructure markup
91faadf home.html: Use classes from Materialize and coalaCSS
9fbd280 getinvolved.html: Rorganise classes and use coalaCSS
ff5a823 about.html: Use styles from Materialize and coalaCSS
6c97863 index.html: Rearrange container class and use MaterializeCSS columns
dfdb4db footer.html: Use Materialize Classes for Grids and Styling
cec0b1d index.html: Add coala CSS CDN link

Looks really nice :+1:

**Pull request merged**
