### PR TITLE
style.css: Increase height of snippets code container

### PR DESCRIPTION
**Pull request by hemangsk**
wrt 	00ed2a4
screen shot 2017-01-31 at 1 31 22 am

wrt 	bc7659d 7ec4f93

### CODE REVIEW

**Comment by Makman2** [comment]
yes looks good :)

**Comment by hemangsk** [comment]
@rultor merge

**Comment by hemangsk** [comment]
reack 1d01145 1aaf15e f7568a5

**Comment by hemangsk** [comment]
@rultor merge

**Pull request merged**
