### PR TITLE
style.css: Change cursor to pointer on available bears link

### PR DESCRIPTION
**Pull request by kaustubhhiware**
style.css: Change cursor to pointer on available bears link

The link for available bears does not look clickable at first. These changes ensure user-friendliness.
Current version : 
current

After this PR : 
change

Closes https://github.com/coala/landing-frontend/issues/150

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by hemangsk** [comment]
add -> Add in the short log. Everything else looks good. :)

**Comment by kaustubhhiware** [comment]
@hemangsk  Thanks :+1: Updated

**Comment by hemangsk** [comment]
@kaustubhhiware You'll have to amend the commit message with,
```git commit --amend``` and then force push.

**Comment by kaustubhhiware** [comment]
This PR is ready to be merged. The requested changes have been made.

**Comment by hemangsk** [comment]
Hey, @kaustubhhiware I just noticed a few things in the commit short log, I missed it initially, the "Add cursor hover for available bears" can be reframed. As presently its a little bit unclear from the short log that what is meant by "available bears", that is, whether we are talking about available bear cards in the language section, or link to available bears. Maybe ```Change cursor to pointer on available bears link```. What do you say?

**Comment by kaustubhhiware** [comment]
I'll make the changes. The version you suggested looks better.

**Comment by hemangsk** [comment]
ack 9cf5faa

**Comment by hemangsk** [comment]
@rultor merge!

**Pull request merged**
