### PR TITLE
about.html: Change statement to right direction

### LINKED ISSUE #222: 'click here' in the About section is not a link
it should either link somewhere or get removed.

### PR DESCRIPTION
**Pull request by khanchi97**
Changed 'click here' to 'click below' because it was not
directing to any link.

Fixes #222

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by khanchi97** [comment]
Hello @prnvdixit but i can see, this issue is open in present #222

**Comment by prnvdixit** [comment]
@khanchi97 Actually I was talking about the second commit - 1112089a6eb9548ae47bde0e2e2f4834a469d4d7, that patch is for an issue (https://github.com/coala/landing-frontend/issues/224) which is already merged in https://github.com/coala/landing-frontend/pull/229.... Your first commit - 9f1ee06687a63390d1156c74641cc75975c50047  is perfect :+1:

**Comment by khanchi97** [comment]
Ok i got it @prnvdixit :smile:

**Comment by khanchi97** [comment]
@prnvdixit i've made the required changes.

**Comment by hemangsk** [comment]
@rultor merge

**Pull request merged**
