### PR TITLE
home.html: Wrap --pre in a  code tag

### PR DESCRIPTION
**Pull request by gabru-md**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by gabru-md** [comment]
yes ma'am! 
i'll do it and notify you. 
Thanks !

**Comment by gabru-md** [comment]
@IpshitaC I have squashed my commits into single one.
with the commit message : "Fixes #163 Changed tags"
Please Review . Thanks . :D

**Comment by IpshitaC** [comment]
ack 0042f716ef88b078ed02a4d5dbc639441752b8c3

**Comment by gabru-md** [comment]
coala1
coala2

Tags were changed on index page and about page.
So i've posted 2 screenshots.

**Comment by gabru-md** [comment]
@hemangsk Please Review

**Comment by hemangsk** [comment]
Hey @gabru-md , really sorry for delay in the review I was badly stuck in some university work. Actually looking at the screenshot, using code tag is definitely changing the overall feel, imo pre was better, but I think maybe Adhityaa had something else in mind? ping @adtac, could you please take a look on this when you get some time?

**Comment by adtac** [comment]
Oh no, I think you've misunderstood my issue. You see the "You can append --pre to that command to get the latest prerelease straight from master!" line in the homepage? The "--pre" part of the line should be within a code tag. That's it. I didn't mean to ask to change all the code elements - just change the "--pre" part to "<code>--pre</code>".

Apologies if it was unclear.

@hemangsk @gabru-md

**Comment by gabru-md** [comment]
@adtac okay! 
No problem I'll make the necessary changes.

**Comment by gabru-md** [comment]
@IpshitaC @adtac Please see. I have made the changes.

**Comment by jayvdb** [comment]
The tone of your commit message needs to be fixed.

Use shortlog
> home.html: Wrap --pre in a code tag

No need for an extra repetitive sentence in the commit body

Just a blank line and the `Closes...` line which you already have done.

**Comment by jayvdb** [comment]
ack https://github.com/coala/landing-frontend/pull/216/commits/450b2a496aa2709ac09712896a21fe3e566b5bde

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
