### PR TITLE
Fix issue 34

### PR DESCRIPTION
**Pull request by gkrishnan724**
Closes: https://github.com/coala/landing-frontend/issues/34

### CODE REVIEW

**Comment by hemangsk** [comment]
Looks good in the browser. Just a suggestion, it'd be nice to have screenshots in PR related to design changes, whatsay?

**Comment by gkrishnan724** [comment]
@hemangsk  Oops sorry, am I supposed to put a screenshot in the screenshots folder?

Here is the  screenshot(Desktop screen):
screenshot from 2017-01-24 17-54-08

Small screen:
screenshot from 2017-01-24 17-59-42





Looks Good?

**Comment by SiddharthKumar02** [comment]
@gkrishnan724 It looks great in the browser. @hemangsk These screenshots can be added in the screenshots folder too.

**Comment by sils** [comment]
ack https://github.com/coala/landing-frontend/pull/42/commits/e22ad85f1a4ea56c33d5f46558100c8e623c2da8 https://github.com/coala/landing-frontend/pull/42/commits/74fe9fbee561242532786e810c633f1182b6fbce

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
