### PR TITLE
about.html: Fix link to point to bears docs

### PR DESCRIPTION
**Pull request by cornu-ammonis**
The link pointed to http://coala.io/#!/languages, it now points to
https://coala.io/#/languages.

Closes https://github.com/coala/landing-frontend/issues/232

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by cornu-ammonis** [comment]
@prnvdixit Done! Sorry about that 😄

**Comment by cornu-ammonis** [comment]
@prnvdixit Ok, I believe my commit message now adheres to the commit guidelines 😃

**Comment by prnvdixit** [comment]
@cornu-ammonis You actually changed the PR description 😉. Please, use ```git commit -a --amend``` to amend your commit. 👍

**Comment by cornu-ammonis** [comment]
@prnvdixit Having some trouble pushing the edit appropriately...did I do it right?

**Comment by prnvdixit** [comment]
You have to squash the commits actually. 👍

**Comment by cornu-ammonis** [comment]
@prnvdixit I tried squashing as per some instructions online but now there are a bunch of other changes showing up under my commit ☹️

**Comment by cornu-ammonis** [comment]
@prnvdixit There must be a simpler way to do this. Should I just get rid of this pull request, create a new branch and commit, and PR that one?

**Comment by prnvdixit** [comment]
First checkout to a point till which you think no ```other changes``` had appeared - Then, carry on from there onward.

**Comment by cornu-ammonis** [comment]
@prnvdixit I dont understand what you mean :(

**Comment by cornu-ammonis** [comment]
@prnvdixit Why can't I just start from scratch? I've googled but can't squash these commits appropriately, I'm in over my head with the git details here, so why not just create a distinct branch / commit?

**Comment by cornu-ammonis** [comment]
@prnvdixit ok, is it appropriate now?

**Comment by cornu-ammonis** [comment]
@prnvdixit Oops :P now it has the issue reference

**Comment by cornu-ammonis** [comment]
@prnvdixit Are you saying I should change the shortlog or the commit body to that text ?

**Comment by prnvdixit** [comment]
@cornu-ammonis See edit. 😉

**Comment by cornu-ammonis** [comment]
@prnvdixit  Like so?

**Comment by cornu-ammonis** [comment]
@prnvdixit Thanks for helping a newbie 👍

**Comment by cornu-ammonis** [comment]
@prnvdixit Is there anything else I need to do to get this merged, or do I just need to wait?

**Comment by cornu-ammonis** [comment]
Oh i think perhaps someone needs to do the "ack {sha}" command?

**Comment by prnvdixit** [comment]
@cornu-ammonis Actually No - Your changes will be approved by any owner before merging the PR. But, for cutting short the review queue line (and helping us to get to your PR early 😃) - you can try to review other PRs in the review queue [here](https://coala.io/review) 😉.

**Comment by cornu-ammonis** [comment]
@prnvdixit  Great -- but I'm confused, when will the pending review tag get removed now that it's merged? I dont want it clogging up the queue 😅

**Comment by hemangsk** [comment]
Merged PR don't show up in the queue ;)

**Pull request merged**
