### PR TITLE
Remove tabs.html

### LINKED ISSUE #19: tabs.html in partials seems to be redundant
@hemangsk can it be deleted?

### PR DESCRIPTION
**Pull request by SiddharthKumar02**
tabs.html in partials seems to be redundant
closes #19

### CODE REVIEW

**Comment by SiddharthKumar02** [comment]
@hemangsk Is this good for a merge?

**Comment by hemangsk** [comment]
Looks good 👍 
- Try checking the changes locally
- Commit should follow the guidelines on [coala.io/commit](http://coala.io/commit)

**Comment by SiddharthKumar02** [comment]
@hemangsk Everything checks out locally :)

**Comment by hemangsk** [comment]
Cool, make sure it follows the commit guidelines, closes -> Closes and newline between issue reference and commit body. 
Also, since you've confirmed that tabs.html is redundant, it'd be good if commit body reflects that. Right now the commit body implies that we're yet unsure if tabs.html is redundant.

**Comment by SiddharthKumar02** [comment]
@hemangsk I made the necessary changes. Is it alright now?

**Comment by hemangsk** [comment]
ack f6591fe

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
